export const STARSHIPS_SUCCESS = "STARSHIPS_SUCCESS";
export const STARSHIPS_ERROR = "STARSHIPS_ERROR";
export const STARSHIPS_MINMAX = "STARSHIPS_MINMAX";
export const STARSHIPS_PICK = "STARSHIPS_PICK";
